### ISSUE TITLE
[PE-D][Tester B] DG: Wrong indentation for Adding an Appointment in Appendix: Instructions for manual testing

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-3/tp#198]
![image.png](https://raw.githubusercontent.com/EthanLoww/ped/main/files/0021e36f-bc40-4d6f-afca-ed5488919abd.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: EthanLoww/ped#5

**Comment by bmanara** [comment]
Linked closed PR resolves issue
