### ISSUE TITLE
[PE-D][Tester D] Header "Adding an appointment" is indented

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-3/tp#201]
Header indentation is inconsistent.
![image.png](https://raw.githubusercontent.com/colinac/ped/main/files/dab676a9-4999-43c1-8f56-ac9fdef92820.png)

![image.png](https://raw.githubusercontent.com/colinac/ped/main/files/bd7aa9a5-bbe3-4339-9272-feb89b59e592.png)
"Adding an appointment" should be at the same level as "Deleting a person". 

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: colinac/ped#1

**Comment by bmanara** [comment]
Issues closed with linked closed PR
