### ISSUE TITLE
[PE-D][Tester B] Add Patient Command: Able to add patient with a future birth date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-3/tp#220]
It would be a good idea to validate the birth date before adding a patient.

![image.png](https://raw.githubusercontent.com/EthanLoww/ped/main/files/90cad424-73f6-4518-a4e0-043efbd44e4f.png)

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: EthanLoww/ped#13

**Comment by bmanara** [comment]
Closing issue, due to linked closed PR
