### ISSUE TITLE
[PE-D][Tester C] Address field length limit

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-3/tp#223]
Might be worth applying a max length limit on the address input. Despite being dealt with in the UI with a '...' for inputs longer than the screen width, it would be logical to set a cap on the address length like a lot of software which take in address fields as inputs.

This would apply to add-doctor and add-patient

![Screenshot 2024-11-08 at 4.42.49 PM.png](https://raw.githubusercontent.com/adipanda2002/ped/main/files/b2eed830-c099-4123-a4e1-bdfa62344621.png)

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: adipanda2002/ped#6

**Comment by bmanara** [comment]
Closing issue as we will not be fixing this. We believe that the user should be able to decide what is too long of an address, and what is not.
