### ISSUE TITLE
[PE-D][Tester A] Address field is not used in solving problems

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-T09-3/tp#242]
All the use cases does not mention any use of address. I think address information may not be so relevant in helping clinics to manage appointments among patients and doctors. It will be better to remove or made optional. Otherwise, it may make typing command inconvenient. 

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: CYX22222003/ped#11

**Comment by MiloTruck** [comment]
Don't believe we need to fix this, it's there for users to know the patient/doctor's address.

**Comment by bmanara** [comment]
Closing this issue as we believe that it is a very small problem/feature flaw. We believe that the address information is still important to our target user, even if it seems like our app does not make use for it
