### ISSUE TITLE
[PE-D][Tester A] The use of parameters is a bit confusing

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-T09-3/tp#271]
Both tag in patient and time in appointment are using `/t`. It may be a bit confusing for users. 

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: CYX22222003/ped#19

**Comment by MiloTruck** [comment]
We don't feel there's a need to fix this as appointment time and patient tags will never be used in the same command.

**Comment by bmanara** [comment]
Closing this issue as we believe that this is a small issue. Since `/t` is used by 2 completely different commands, this distinction should be somewhat clear and is not a priority to change/improve.
